---
trigger:
  - master
pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
steps:
  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildId)'
      repository: hema789/chaitu
  - task: Docker@2
    inputs:
      command: 'push'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildId)'
      repository: hema789/chaitu
      buildContext: '**'

      

      
