---
apiVersion: v1
kind: Pod
metadata:
  name: nopcommerce
spec:
  containers:
    - name: nop
      image: hema789/nop:latest
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: nop-service
spec:
  type: LoadBalancer
  ports:
    - name: nop
      port: 8080
      targetPort: 80

      
