---
pool: Default
trigger: 
steps:
  - task: Maven@4
    inputs:
      mavenPOMFile: 'pom.xml' 
      goals: 'package'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      allowBrokenSymlinks: true
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 3.6.3
    displayName: build
    timeoutInMinutes: 60

  


