---
pool: Azure pipelines
trigger:
  - main
steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
       codeCoverageClassFilesDirectories: 'build/classes/main/
       javaHomeOption: 'JDKVersion'
       publishJUnitResults: true
       javaHomeOption: 'JDKVersion'
       continueOnError: true
