---

pool: 
  name: Azure Pipelines
  vmImage: ubuntu-latest
trigger:
  - main
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'aws-terraform'
    backendAWSBucketName: 'pulihora22'
    backendAWSKey: 'statefiles/sample.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'aws-terraform'
    backendAWSBucketName: 'pulihora22'
    backendAWSKey: 'statefiles/sample.tfstate' 
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'aws-terraform'
    backendAWSBucketName: 'pulihora22'
    backendAWSKey: 'statefiles/sample.tfstate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'destroy'
    environmentServiceNameAWS: 'aws-terraform'

