---
pool: 
  name: Default
  vmImage: ubuntu-latest
trigger:
  - main
steps:
  - script: pwd
  - script: terraform init 
  - script: terraform validate
  - script: terraform apply -auto-approve
  - script: terraform destroy -auto-approve


