---
pool: 
  name: Azure Pipelines
  vmImage: ubntu-latest
trigger:
  - main
steps:
  - script: terraform init 
  - script: terraform validate
  - script: terraform plan -auto-approve
  - script: terraform apply -auto-approve


