---

pool: 
  name: Azure Pipelines
  vmImage: ubuntu-latest
trigger:
  - main
steps:

  - task: TerraformTaskV4@4
    inputs:
      provider: 'aws'
      command: 'init'
      backendServiceAWS: 'aws-terraform'
      backendAWSBucketName: 'pulihora22'
      backendAWSKey: 'chaitu/vartf.tfvars'
  - script: pwd
  - script: terraform init 
  - script: terraform validate
  - script: terraform apply -auto-approve
  - script: terraform destroy -auto-approve


