---
trigger:
  - main
jobs:
  - j0b: 'build-maven'
    displayName: build maven in spring petclinic
    continueOnError: yes
    pool:
      name: Azure Pipelines
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      inputs:
        mavenPOMFile: 'pom.xml'
        goals: 'package'
        
    